# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='test',
        ),
    ]
